# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('genre', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
