# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-29 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181129_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
