# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-29 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hall_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='seat',
        ),
    ]
