# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_schedule_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.ManyToManyField(to='main.TimeSlot'),
        ),
    ]
