# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181203_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
