# Generated by Django 2.2.6 on 2019-12-01 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191127_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cinemas',
            },
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='halls',
            options={'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='orderedseats',
            options={'verbose_name_plural': 'OrderedSeats'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='schedules',
            options={'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='seats',
            options={'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2019, 12, 1)),
        ),
        migrations.AddField(
            model_name='halls',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Cinemas'),
            preserve_default=False,
        ),
    ]
