# Generated by Django 2.2.6 on 2019-12-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191201_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdb_link',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
