# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_schedule_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
