# Generated by Django 2.2.6 on 2019-12-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movies_imdb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb_link',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
