# Generated by Django 2.2.6 on 2019-12-02 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191201_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2019, 12, 2)),
        ),
    ]
