# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 06:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181205_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(default=datetime.date(2018, 12, 5))),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Schedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seat')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order')),
            ],
        ),
    ]
