# Generated by Django 2.0 on 2019-12-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20191204_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cinemas')),
            ],
            options={
                'verbose_name_plural': 'CinemaRatings',
            },
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cinemas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserRatings',
            },
        ),
    ]
