# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181205_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Schedule'),
        ),
    ]
