# Generated by Django 2.0 on 2019-12-04 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cinemarating_userratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemarating',
            name='cinema',
        ),
        migrations.AddField(
            model_name='cinemas',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2019, 12, 5)),
        ),
        migrations.DeleteModel(
            name='CinemaRating',
        ),
    ]
