# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-06 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181205_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=50, null=True)),
                ('phone_number', models.TextField(max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2018, 12, 6)),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customers'),
        ),
    ]
