# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181207_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='id',
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.TextField(default='Orange', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Hall'),
        ),
    ]
