# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181207_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
