# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-07 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181207_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2018, 12, 8)),
        ),
    ]
