# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-09 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20181208_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customers'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Schedule'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Seat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2018, 12, 10)),
        ),
    ]
