# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-09 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181210_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
