# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20181211_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
    ]
