# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20181211_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='schedule_id',
        ),
    ]
