# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20181211_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedseats',
            name='schedule_id',
        ),
    ]
