# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_orderedseats_schedule_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
        migrations.RenameModel(
            old_name='Hall',
            new_name='Halls',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedules',
        ),
        migrations.RenameModel(
            old_name='Seat',
            new_name='Seats',
        ),
    ]
