# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-12 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20181211_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2018, 12, 12)),
        ),
    ]
