# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20181212_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
