# Generated by Django 2.0 on 2019-10-07 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190406_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.TimeField(default=datetime.date(2019, 10, 7)),
        ),
    ]
